# Generated by Django 3.0 on 2021-06-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210615_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentadvisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invest_advisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
