# Generated by Django 3.0 on 2021-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210615_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentadvisor',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentadvisor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
