# Generated by Django 3.0 on 2021-06-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210615_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='drawdown_behavior',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Усреднение'), (1, 'Терпимое отношение'), (2, ' Продажа части акций'), (3, 'Закрытие портфеля')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='employment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Работает по найму'), (1, 'Самозанятый'), (2, 'Предприниматель'), (3, 'Не работает')]),
        ),
    ]
