# Generated by Django 3.0 on 2021-06-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_client_investmen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='drawdown_behavior',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Усреднение'), (1, 'Терпимое отношение'), (2, 'Продажа части акций'), (3, 'Закрытие портфеля')]),
        ),
    ]
