# Generated by Django 3.0 on 2021-06-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_client_investmen'),
        ('portfolio', '0004_auto_20210618_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='investmen',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
            preserve_default=False,
        ),
    ]
