# Generated by Django 3.0 on 2021-06-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210620_0228'),
        ('portfolio', '0005_auto_20210618_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='draft',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='ETF',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Да'), (1, 'Нет'), (2, 'Только в ETF')]),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='users.Client'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Доллары'), (1, 'Рубли')], verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='focus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Минимальные просадки'), (1, 'Максимальная прибыль')], verbose_name='фокус'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type_according_risk_reward',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Агрессивный'), (1, 'Консервативный'), (2, 'Сбалансированный')], verbose_name='тип по соотношению риска/прибыли'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type_investor',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Квалифицированный инвестор'), (1, 'Неквалифицированный инвестор')], verbose_name='тип инвестора'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='types_assets',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Акции российских компаний'), (1, 'Международные акции'), (2, 'Торговые рынки')], verbose_name='тип акций'),
        ),
    ]
