# Generated by Django 3.0 on 2021-06-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210620_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='draft',
            new_name='active',
        ),
    ]
