# Generated by Django 3.0 on 2021-06-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210620_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sector_blacklist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='portfolio.Portfolio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='share',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
