# Generated by Django 3.0 on 2021-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210622_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='investment_strategy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'по умолчанию'), (1, 'Фокус на рост'), (2, 'Фокус на диверсификацию')], default=1, verbose_name='инвестиционная стратегия'),
            preserve_default=False,
        ),
    ]
