# Generated by Django 3.0 on 2021-06-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolio_investment_strategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='cost_in_dollars',
        ),
        migrations.AddField(
            model_name='stock',
            name='access_to_unqualified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='cost_in_rubles',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='types_assets',
            field=models.TextField(),
        ),
    ]
