# Generated by Django 3.0 on 2021-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20210629_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='access_to_unqualified',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cost_in_dollars',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cost_in_rubles',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='share',
            field=models.PositiveIntegerField(),
        ),
    ]
