# Generated by Django 3.0 on 2021-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210722_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='share',
            field=models.FloatField(),
        ),
    ]
