# Generated by Django 3.0 on 2021-07-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210722_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='share',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
