# Generated by Django 3.0 on 2021-07-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20210722_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='share',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
