# Generated by Django 3.0 on 2021-07-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20210722_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='share',
            field=models.FloatField(),
        ),
    ]
