# Generated by Django 3.0 on 2021-07-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210726_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='portfolio.Ticker'),
        ),
        migrations.AlterField(
            model_name='tickervalue',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_value', to='portfolio.Ticker'),
        ),
    ]
