# Generated by Django 3.0 on 2021-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_portfolio_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='value_share',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
