# Generated by Django 3.0 on 2021-07-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_stock_value_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='value_share',
            field=models.FloatField(blank=True),
        ),
    ]
