# Generated by Django 3.0 on 2021-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20210728_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
