# Generated by Django 3.0 on 2021-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20210731_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='true_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='type_according_risk_reward',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
