# Generated by Django 3.0 on 2021-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20210731_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='etf',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
