# Generated by Django 3.0 on 2021-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_ticker_etf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='maximum_allowable_drawdown',
            field=models.FloatField(verbose_name='максимально допустимая просадка'),
        ),
    ]
