# Generated by Django 3.0 on 2021-08-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20210802_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='shares_blacklist',
            field=models.TextField(blank=True),
        ),
    ]
