# Generated by Django 3.0 on 2021-08-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20210812_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='value_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
